# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='instruction',
            new_name='introduction',
        ),
    ]
